@extends('layouts.front')

@section('content')
<div class="about-section ">

        <div class="container">
            <div class="disc-sec">
                <div class="disc-sec ">
                    <div class="container">
                        <h2>Cookie Policy</h2>
                        <div class="upd-text">Updated at 2021-12-17</div>

                        <div class="row mb-3">
                            <div class="col-12 mb-3">
                                <div class="val-sub-text">
                                    To help explain things as clearly as possible in this Cookie Policy, every time any of these terms are referenced, are strictly
                                    defined as:
                                </div>

                            </div>
                            <ul class="mx-4 sub-deta-cool">
                                <li>
                                    Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
                                    provide analytics, remember information about you such as your language preference or login information.
                                </li>
                                <li>
                                    Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Velox Solution, that is responsible for your
                                    information under this Cookie Policy
                                </li>
                                <li>
                                   Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit velox
                                    solution and use the services
                                </li>
                                <li>
                                    Personal Data: any information that directly, indirectly, or in connection with other information — including a personal
                                    identification number — allows for the identification or identifiability of a natural person.
                                </li>
                                <li>
                                    Service: refers to the service provided by Velox Solution as described in the relative terms (if available) and on this platform.
                                </li>
                                <li>
                                    Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide
                                    our content or whose products or services we think may interest you.
                                </li>
                                <li>
                                   Website: Velox Solution."’s" site, which can be accessed via this URL: https://veloxsolution.com/
                                </li>
                                <li>
                                    You: a person or entity that is registered with Velox Solution to use the Services.
                                </li>
                            </ul>
                        </div>

                        <h2>Introduction</h2>
                        <div class="val-sub-text mb-3">
                            This Cookie Policy explains how Velox Solution and its affiliates (collectively "Velox Solution", "we", "us", and "ours"), use cookies
                            and similar technologies to recognize you when you visit our website/app, including without limitation https://veloxsolution.com/
                            and any related URLs, mobile or localized versions and related domains / sub-domains ("Websites"). It explains what these
                            technologies are and why we use them, as well as the choices for how to control them.
                        </div>

                        <h2>What is a cookie?</h2>
                        <div class="val-sub-text mb-3">
                            A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser,
                            provide analytics, remember information about you such as your language preference or login information. They're completely
                            safe and can't be used to run programs or deliver viruses to your device.
                        </div>

                        <h2>Why do we use cookies?</h2>
                        <div class="val-sub-text mb-3">
                            We use first party and/or third party cookies on our website/app for various purposes such as:
                        </div>

                       <ul class="mx-4 sub-deta-cool">
                            <li>
                                  To facilitate the operation and functionality of our website/app;
                            </li>
                            <li>
                                To improve your experience of our website/app and make navigating around them quicker and easier;
                            </li>
                            <li>
                               To allow us to make a bespoke user experience for you and for us to understand what is useful or of interest to you;
                            </li>
                            <li>
                                To analyze how our website/app is used and how best we can customize it;
                            </li>
                            <li>
                                To identify future prospects and personalize marketing and sales interactions with it;
                            </li>
                             <li>
                               To facilitate the tailoring of online advertising to your interests.
                            </li>
                        </ul>

                        <h2>What type of cookies does Velox Solution use?</h2>
                        <div class="val-sub-text mb-3">
                            Cookies can either be session cookies or persistent cookies. A session cookie expires automatically when you close your
                            browser. A persistent cookie will remain until it expires or you delete your cookies. Expiration dates are set in the cookies
                            themselves; some may expire after a few minutes while others may expire after multiple years. Cookies placed by the website
                            you’re visiting are called “first party cookies”.
                        </div>
                        <div class="val-sub-text mb-3">
                            Strictly Necessary cookies are necessary for our website/app to function and cannot be switched off in our systems. They are
                            essential in order to enable you to navigate around the website/app and use its features. If you remove or disable these cookies,
                            we cannot guarantee that you will be able to use our website/app.
                        </div>
                        <div class="val-sub-text mb-4">
                            We use the following types of cookies in our website/app:
                        </div>

                        <h2>Performance and Functionality Cookies</h2>
                        <div class="val-sub-text mb-4">
                            These cookies are used to enhance the performance and functionality of our website/app but are non-essential to their use.
                            However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your
                            login details every time you visit the website/app as we would not be able to remember that you had logged in previously.
                        </div>

                        <h2>Social Media Cookies</h2>
                        <div class="val-sub-text mb-4">
                            These cookies are used when you share information using a social media sharing button or “like” button on our Site or you link
                            your account or engage with our content on or through a social networking website such as Facebook, Twitter or Google+. The
                            social network will record that you have done this. These cookies may also include certain code that has been placed on the
                            platform to help track conversions from ads, optimize ads based on collected data, build targeted audiences for future ads, and
                            remarket to qualified users who have already taken certain action on the platform.
                        </div>


                        <h2>Third Party Cookies</h2>
                        <div class="val-sub-text mb-4">
                            Some cookies that have been set on our website/app are not set on a first party basis by Velox Solution. The Websites can be
                            embedded with content from third parties to serve advertising. These third party service providers may set their own cookies on
                            your web browser. Third party service providers control many of the performance and functionality, advertising, marketing and
                            analytics cookies described above. We do not control the use of these third party cookies as cookies can only be accessed by
                            the third party that originally set them.
                        </div>

                        <h2>How you can manage cookies?</h2>
                        <div class="val-sub-text mb-3">
                            Most browsers allow you to control cookies through their 'settings' preferences. However, if you limit the ability of websites to set
                            cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may also stop you from
                            saving customized settings like login information. Browser manufacturers provide help pages relating to cookie management in
                            their products.
                        </div>
                        <div class="val-sub-text mb-4">
                            Browser manufacturers provide help pages relating to cookie management in their products. Please see below for more
                            information.
                        </div>


                        <ul class="mx-4 sub-deta-cool">
                            <li>
                                 Google Chrome
                            </li>
                            <li>
                                Internet Explorer
                            </li>
                            <li>
                                Mozilla Firefox
                            </li>
                            <li>
                                 Safari (Desktop)
                            </li>
                            <li>
                                Safari (Mobile)
                            </li>
                             <li>
                                 Android Browser
                            </li>
                             <li>
                                 Opera
                            </li>
                             <li>
                                 Opera Mobile
                            </li>
                        </ul>

                        <h2>Blocking and disabling cookies and similar technologies</h2>
                        <div class="val-sub-text mb-4">
                            Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our
                            essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features
                            and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site
                            preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a
                            cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your
                            browser, you should visit your browser's help menu for more information.
                        </div>

                        <h2>Changes To Our Cookie Policy</h2>
                        <div class="val-sub-text mb-4">
                            We may change our Service and policies, and we may need to make changes to this Cookie Policy so that they accurately
                            reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before
                            we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect. Then, if you
                            continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to this or any updated
                            Cookie Policy, you can delete your account.
                        </div>

                        <h2>Your Consent</h2>
                        <div class="val-sub-text mb-3">
                            By using our website/app, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to
                            its terms.
                        </div>

                        <h2>Contact Us</h2>
                          <div class="val-sub-text mb-4">Don't hesitate to contact us if you have any questions regarding our Cookie Policy.</div>
                          <ul class="mx-4 sub-deta-cool">
                            <li class="mb-5">
                              Via this Link: https://veloxsolution.com/
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
</div>
@endsection

@section('scripts')



@endsection
