@extends('layouts.front')

@section('content')
<div class="about-section ">

        <div class="container">
            <div class="disc-sec">
                <div class="disc-sec ">
                    <div class="container">
                        <h2>Disclaimer</h2>
                        <div class="upd-text">Updated at 2021-12-17</div>
                        <div class="row my-3">
                            <div class="col-12">
                                <div class="val-sub-text">
                                    Velox Solution hereby grants you access to https://veloxsolution.com/ (“the Website”) and invites you to purchase the services
                                    offered here.
                                </div>
                            </div>
                        </div>
                        <h2>Disclaimer</h2>
                        <div class="row">
                            <div class="col-12 mb-3">
                                <div class="val-sub-text">
                                   To help explain things as clearly as possible in this Disclaimer, every time any of these terms are referenced, are strictly defined
                                    as:
                                </div>

                            </div>
                            <ul class="mx-4 sub-deta-cool">
                                <li>
                                    Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
                                    provide analytics, remember information about you such as your language preference or login information.
                                </li>
                                <li>
                                    Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to velox doorstep services pvt ltd, 401
                                    poonam avenue mehulnagar jamnagar that is responsible for your information under this Disclaimer.
                                </li>
                                <li>
                                    Service: refers to the service provided by Velox Solution as described in the relative terms (if available) and on this platform.
                                </li>
                                <li>
                                    Website: Velox Solution."’s" site, which can be accessed via this URL: https://veloxsolution.com
                                </li>
                                <li>
                                    You: a person or entity that is registered with Velox Solution to use the Services.
                                </li>
                            </ul>
                        </div>

                        <h2>Limited liability</h2>
                        <div class="val-sub-text mb-3">
                            Velox Solution endeavours to update and/or supplement the content of the website/app on a regular basis. Despite our care and
                            attention, content may be incomplete and/or incorrect.
                        </div>
                        <div class="val-sub-text mb-3">
                            The materials offered on the website/app are offered without any form of guarantee or claim to their correctness. These
                            materials can be changed at any time without prior notice from Velox Solution.
                        </div>
                        <div class="val-sub-text mb-3">
                            Particularly, all prices on the website/app are stated subject to typing and programming errors. No liability is assumed for the
                            implications of such errors. No agreement is concluded on the basis of such errors.
                        </div>
                        <div class="val-sub-text mb-3">
                           Velox Solution shall not bear any liability for hyperlinks to websites or services of third parties included on the website/app. From
                            our website/app, you can visit other websites by following hyperlinks to such external sites. While we strive to provide only
                            quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other
                            websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without
                            notice and may occur before we have the opportunity to remove a link which may have gone ‘bad’.
                        </div>
                        <div class="val-sub-text mb-4">
                           Please be also aware that when you leave our website/app, other sites may have different privacy policies and terms which are
                            beyond our control. Please be sure to check the Privacy Policies of these sites as well as their "Terms of Service" before
                            engaging in any business or uploading any information.
                        </div>


                        <h2>Links to Other Websites Disclaimer</h2>
                        <div class="val-sub-text mb-3">
                        This Disclaimer applies only to the Services. The Services may contain links to other websites not operated or controlled by
                        Velox Solution. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are
                        not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other
                        website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties
                        may use their own cookies or other methods to collect information about you. If You click on a third party link, You will be
                        directed to that third party's site. We strongly advise You to review the Privacy Policy and Terms of every site You visit.
                        </div>

                        <div class="val-sub-text mb-4">
                        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or
                        services.
                        </div>

                        <h2>Errors and Omissions Disclaimer</h2>

                        <div class="val-sub-text mb-3">Velox Solution is not responsible for any content, code or any other imprecision.</div>
                        <div class="val-sub-text mb-3">Velox Solution does not provide warranties or guarantees.</div>
                        <div class="val-sub-text mb-3">
                            In no event shall Velox Solution be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service
                            or the contents of the Service. Velox Solution reserves the right to make additions, deletions, or modifications to the contents on
                            the Service at any time without prior notice.
                        </div>

                        <h2>General Disclaimer</h2>
                        <div class="val-sub-text mb-4">
                            The Velox Solution Service and its contents are provided "as is" and "as available" without any warranty or representations of         any kind, whether express or implied. Velox Solution is a distributor and not a publisher of the content supplied by third parties;
                            as such, Velox Solution exercises no editorial control over such content and makes no warranty or representation as to the
                            accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the velox
                            solution Service. Without limiting the foregoing, Velox Solution specifically disclaims all warranties and representations in any
                            content transmitted on or in connection with the Velox Solution Service or on sites that may appear as links on the Velox Solution
                            Service, or in the products provided as a part of, or otherwise in connection with, the Velox Solution Service, including without
                            limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral
                            advice or written information given by Velox Solution or any of its affiliates, employees, officers, directors, agents, or the like will
                            create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, velox
                            solution does not warrant that the Velox Solution Service will be uninterrupted, uncorrupted, timely, or error-free.
                        </div>

                        <h2>Copyright Disclaimer</h2>
                        <div class="val-sub-text mb-4">
                            All intellectual property rights concerning these materials are vested in Velox Solution. Copying, distribution and any other use of these materials is not permitted without the written permission of Velox Solution, except and only to the extent otherwise
                            provided in regulations of mandatory law (such as the right to quote), unless otherwise stated for certain materials.
                        </div>

                        <h2>Affiliate Links Disclosure</h2>
                        <div class="val-sub-text mb-4">
                            Velox Solution has affiliate links and in this section of the Disclaimer we will address how we use those affiliate links from other websites/companies and products. These “affiliate links” are specific URLs that contain the affiliate's ID or username.
                        </div>

                        <div class="val-sub-text mb-4">
                            In compliance with the FTC guidelines, please assume the following about links and posts on this site:
                        </div>

                        <ul class="mx-4 sub-deta-cool">
                            <li>
                                Any/all of the links on Velox Solution are affiliate links of which we receive a small commission from sales of certain items,
                                but the price is the same for you. As Velox Solution has grown, so have costs associated with running and maintaining it,
                                and affiliate links are a way we help offset these costs.
                            </li>
                            <li>
                                If we post an affiliate link to a product, it is something that we personally use, support and would recommend without an
                                affiliate link.
                            </li>
                            <li>
                                Unless otherwise noted, all reviews are of items we have purchased and we are not paid or compensated in any way.
                            </li>
                        </ul>

                        <div class="val-sub-text mb-4">We might participate in affiliate programs such as:</div>
                        <ul class="mx-4 sub-deta-cool">
                            <li>
                              Others
                            </li>
                        </ul>


                        <h2>Legal Disclosure</h2>
                        <div class="val-sub-text mb-4">
                            The materials, any comments or information provided by Velox Solution are for educational purposes only and nothing conveyed or provided should be considered legal, accounting or tax advice. You are responsible for whatever you may do with the
                            information you obtain from Velox Solution. As such, by visiting and using this website/app you acknowledge and agree that you
                            have been assessed by a qualified law expert (i.e your attorney) who has given you consent to take part in any legal activity.
                            Please contact your own attorney, accountant or tax professional with any specific questions you have related to the information
                            provided that are of legal, accounting or tax nature.
                        </div>

                        <h2>Testimonials Disclosure</h2>
                        <div class="val-sub-text mb-4">
                            Any testimonials provided on this platform are opinions of those providing them. The information provided in the testimonials is not to be relied upon to predict results in your specific situation. The results you experience will be dependent on many factors
                            including but not limited to your level of personal responsibility, commitment, and abilities, in addition to those factors that you
                            and/or Velox Solution may not be able to anticipate.
                        </div>

                        <div class="val-sub-text mb-4">
                            We will give honest testimonials to our visitors regardless of any discount. Any product or service that we test are individual experiences, reflecting real life experiences. The testimonials could be displayed on audio, text or video and are not necessarily
                            representative of all of those who will use our products and/or services.</div>

                        <div class="val-sub-text mb-4">
                            Velox Solution does not guarantee the same results as the testimonials given on our platform. Testimonials presented on Velox Solution are applicable to the individuals writing them, and may not be indicative of future success of any other individuals.
                        </div>

                        <div class="val-sub-text mb-4">
                            Please don’t hesitate to contact us if you would like to know more about testimonials, discounts, or any of the products/services that we review.
                        </div>


                        <h2>Your Consent</h2>
                        <div class="val-sub-text mb-4">
                            We've updated our Disclaimer to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website/app, registering an account, or making a purchase, you hereby consent to our Disclaimer
                            and agree to its terms.
                        </div>

                        <h2>Changes To Our Disclaimer</h2>

                        <div class="val-sub-text mb-4">
                            Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you will be bound by the updated Disclaimer. If you do not want to agree to this or any updated Disclaimer, you can delete your
                            account.
                        </div>

                        <h2>Contact Us</h2>
                          <div class="val-sub-text mb-4">Don't hesitate to contact us if you have any questions regarding this Disclaimer.</div>
                          <ul class="mx-4 sub-deta-cool">
                            <li class="mb-5">
                              Via this Link: https://veloxsolution.com/
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
</div>
@endsection

@section('scripts')



@endsection
