@extends('layouts.front')

@section('content')
<div class="about-section ">

        <div class="container">
            <div class="disc-sec">
                <div class="disc-sec">
                    <div class="container">
                        <h2>Return & Refund Policy</h2>
                        <div class="upd-text mb-4">Updated at 2021-12-17</div>
                        <h2>Definitions and key terms</h2>
                        <div class="val-sub-text mb-3">
                           To help explain things as clearly as possible in this Return & Refund Policy, every time any of these terms are referenced, are
                            strictly defined as:
                        </div>

                         <ul class="mx-4 sub-deta-cool">
                            <li>
                                Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
                                provide analytics, remember information about you such as your language preference or login information.
                            </li>
                            <li>
                                Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to VELOX SOLUTION, that is responsible for
                                your information under this Return & Refund Policy.
                            </li>
                            <li>
                            Customer: refers to the company, organization or person that signs up to use the VELOX SOLUTION Service to manage
                            the relationships with your consumers or service users.
                            </li>
                            <li>
                                Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit
                                VELOX SOLUTION and use the services.
                            </li>
                            <li>
                               Service: refers to the service provided by VELOX SOLUTION as described in the relative terms (if available) and on this
                                platform.
                            </li>
                             <li>
                                Website: VELOX SOLUTION."’s" site, which can be accessed via this URL: https://veloxsolution.com/
                            </li>
                            <li>
                               You: a person or entity that is registered with VELOX SOLUTION to use the Services.
                            </li>
                        </ul>
                        <h2>Return & Refund Policy</h2>
                       <div class="val-sub-text mb-3">
                            Thanks for shopping at VELOX SOLUTION. We appreciate the fact that you like to buy the stuff we build. We also want to make
                            sure you have a rewarding experience while you’re exploring, evaluating, and purchasing our products.
                        </div>
                        <div class="val-sub-text mb-3">
                            As with any shopping experience, there are terms and conditions that apply to transactions at VELOX SOLUTION. We’ll be as
                            brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at VELOX
                            SOLUTION, you agree to the terms set forth below along with Policy
                        </div>
                        <div class="val-sub-text mb-4">
                            If there’s something wrong with the you bought, or if you are not happy with it, you will not be able to issue a refund for your
                            item.
                        </div>


                        <h2>Refunds</h2>
                       <div class="val-sub-text mb-3">
                            We at ourselves to serving our customers with the best products. Every single product that you choose is thoroughly inspected,
                            checked for defects and packaged with utmost care. We do this to ensure that you fall in love with our products.
                        </div>
                        <div class="val-sub-text mb-3">
                           Sadly, there are times when we may not have the product(s) that you choose in stock, or may face some issues with our
                            inventory and quality check. In such cases, we may have to cancel your order. You will be intimated about it in advance so that
                            you don't have to worry unnecessarily about your order. If you have purchased via Online payment (not Cash on Delivery), then
                            you will be refunded once our team confirms your request.
                        </div>
                        <div class="val-sub-text mb-4">
                            We carry out thorough quality check before processing the ordered item. We take utmost care while packing the product. At the
                            same time we ensure that the packing is good such that the items won’t get damaged during transit. Please note that VELOX
                            SOLUTION is not liable for damages that are caused to the items during transit or transportation.
                        </div>

                            <div class="val-sub-text mb-3">
                                We follow certain policies to ensure transparency, efficiency and quality customer care:
                            </div>
                            <ul class="mx-4 sub-deta-cool">
                                <li>
                                  We DO NOT allow returns on sold products - online or in retail outlets.
                                </li>
                                <li>
                                   We DO NOT accept returned goods, as we believe that customers should get the best quality products.
                                </li>
                                <li>
                                   Refunds are NOT given for any purchases made - be they online or in retail store.
                                </li>
                                <li>
                                     We DO NOT encourage exchanges of our products.
                                </li>
                                <li>
                                    We DO NOT engage in reselling used products and discourage the same, because we cannot ensure the best quality
                                    products for our customers.
                                </li>
                            </ul>

                            <div class="val-sub-text mb-3">
                                 For International Orders:
                            </div>
                            <ul class="mx-4 sub-deta-cool">
                                <li>
                                         We DO NOT support Exchanges or Returns.
                                </li>
                                <li>
                                        If you cancel the order before we process it and dispatch for shipping, a refund can be processed. Orders generally take
                                        1-2 days to process before dispatch.
                                </li>
                                <li>
                                  Orders already in shipping cannot be returned, canceled or refunded.
                                </li>
                                <li>
                                    If you face any issues, please contact our Support Team immediately.
                                </li>

                            </ul>

                        <h2>Your Consent </h2>
                        <div class="val-sub-text mb-4">
                            By using our website/app, registering an account, or making a purchase, you hereby consent to our Return & Refund Policy and
                            agree to its terms.
                        </div>


                        <h2>Changes To Our Return & Refund Policy</h2>
                       <div class="val-sub-text mb-4">
                            Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies.
                            Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you
                            will be bound by the updated Return & Refund Policy. If you do not want to agree to this or any updated Return & Refund Policy,
                            you can delete your account.
                        </div>

                        <h2>Contact Us</h2>
                       <div class="val-sub-text mb-3">
                             If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we
                            will discuss any of the issues you are going through with our product.
                        </div>
                        <ul class="mx-4 sub-deta-cool">
                            <li class="mb-5">
                              Via this Link: https://veloxsolution.com/
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
</div>
@endsection

@section('scripts')



@endsection
